version: "3.7"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizza
      MYSQL_USER: esteban
      MYSQL_PASSWORD: qwe123
    ports:
      - "3306:3306"
